project:
  type: website

website:
  title: "blog"
  navbar:
    background: "purple"
    right:
      - about.qmd
      - text: assignments 
      - href: assignment.qmd
        href: index.qmd
      - text: lists
          
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

